# Generated by Django 6.0.5 on 2026-05-11 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('households', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('category', models.CharField(max_length=60)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SustainabilityMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=80)),
                ('recycling_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbon_reduction_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('landfill_reduction_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('segregation_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('measured_on', models.DateField()),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='households.household')),
            ],
        ),
    ]
