# Generated by Django 6.0.5 on 2026-05-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasCylinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=80, unique=True)),
                ('capacity_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fill_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('distributed', 'Distributed'), ('maintenance', 'Maintenance')], default='available', max_length=32)),
                ('last_filled_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MethaneProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_code', models.CharField(max_length=40)),
                ('organic_input_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methane_m3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gas_purity_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pressure_bar', models.DecimalField(decimal_places=2, max_digits=6)),
                ('digester_health_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('measured_at', models.DateTimeField()),
            ],
        ),
    ]
