# Generated by Django 6.0.5 on 2026-05-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=80)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contamination_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estimated_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('warehouse_location', models.CharField(max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
